vich_uploader:
    db_driver: orm # ou odm pour MongoDB
    metadata:
        type: attribute

    mappings:
        images_project:
                uri_prefix: /img/projet # le préfixe de l'URL pour accéder aux fichiers
                upload_destination: '%kernel.project_dir%/public/img/projet' # le chemin où les fichiers seront stockés sur le serveur
                namer: Vich\UploaderBundle\Naming\OrignameNamer # la stratégie de nommage des fichiers
               
                delete_on_update: true



    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
