


controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
img_edit:
    path: /img/edit.png
    controller: App\Controller\IndexController::imgEdit

img_menu:
    path: /img/menu.png

   